export const id = {
  // Nav
  nav_home: "Beranda",
  nav_login: "Masuk",
  nav_register: "Daftar",
  nav_dashboard: "Dasbor",
  nav_logout: "Keluar",

  // Landing
  hero_title: "Kelola Preorder Bisnis Kamu dengan Mudah",
  hero_subtitle:
    "Waitlistku membantu UMKM mengatur sesi preorder, produk, promo, dan pesanan pelanggan — semua dalam satu tempat.",
  hero_cta_register: "Mulai Gratis",
  hero_cta_login: "Masuk",
  feature1_title: "Sesi Preorder Fleksibel",
  feature1_desc:
    "Buat sesi dengan tanggal buka/tutup, link publik, dan kelola produk dengan mudah.",
  feature2_title: "Promo & Diskon Otomatis",
  feature2_desc:
    "Atur promo untuk N pembeli pertama, deadline waktu, atau kode kupon.",
  feature3_title: "Pesanan via WhatsApp",
  feature3_desc:
    "Pelanggan pesan langsung, konfirmasi otomatis dikirim via WhatsApp.",

  // Auth
  login_title: "Masuk ke Waitlistku",
  login_email: "Email",
  login_password: "Kata Sandi",
  login_submit: "Masuk",
  login_no_account: "Belum punya akun?",
  login_register_link: "Daftar sekarang",
  register_title: "Daftar Waitlistku",
  register_business: "Nama Bisnis",
  register_wa: "Nomor WhatsApp",
  register_email: "Email",
  register_password: "Kata Sandi",
  register_confirm: "Konfirmasi Kata Sandi",
  register_submit: "Daftar",
  register_have_account: "Sudah punya akun?",
  register_login_link: "Masuk di sini",

  // Dashboard
  dashboard_title: "Sesi Preorder Saya",
  dashboard_new: "Buat Sesi Baru",
  dashboard_empty: "Belum ada sesi. Buat sesi pertamamu!",
  session_manage: "Kelola",
  session_open_page: "Buka Halaman",
  session_delete: "Hapus",
  session_active: "Aktif",
  session_inactive: "Nonaktif",
  session_orders: "pesanan",
  session_slug: "Link",
  session_copy: "Salin",
  session_copied: "Tersalin!",

  // Session modal
  modal_new_session: "Buat Sesi Baru",
  session_title_label: "Judul Sesi",
  session_intro_label: "Teks Intro",
  session_footer_label: "Teks Footer",
  session_opens_at: "Dibuka Pada",
  session_closes_at: "Ditutup Pada",
  session_active_toggle: "Sesi Aktif",
  btn_save: "Simpan",
  btn_cancel: "Batal",
  btn_create: "Buat",
  btn_delete: "Hapus",
  btn_edit: "Edit",
  btn_edit_settings: "Edit Pengaturan",
  btn_add: "Tambah",
  btn_import: "Import XLSX",
  btn_template: "Unduh Template",
  btn_export: "Export Pesanan",

  // Tabs
  tab_products: "Produk",
  tab_promos: "Promo",
  tab_orders: "Pesanan",
  tab_summary: "Ringkasan",

  // Items
  item_name: "Nama Produk",
  item_desc: "Deskripsi",
  item_price: "Harga",
  item_quota: "Kuota",
  item_quota_limit: "Batasi?",
  item_quota_amount: "Jumlah kuota",
  item_no_quota: "Tidak terbatas",
  item_empty: "Belum ada produk.",
  item_add: "Tambah Produk",
  item_edit: "Edit Produk",

  // Promos
  promo_name: "Nama Promo",
  promo_type: "Tipe Promo",
  promo_price: "Harga Promo",
  promo_type_first_n: "N Pembeli Pertama",
  promo_type_deadline: "Sebelum Deadline",
  promo_type_coupon: "Kode Kupon",
  promo_max_count: "Maks. Pembeli",
  promo_deadline: "Deadline",
  promo_coupon_code: "Kode Kupon",
  promo_applies_to: "Berlaku Untuk",
  promo_applies_session: "Seluruh Sesi",
  promo_applies_item: "Item Tertentu",
  promo_select_item: "Pilih Item",
  promo_empty: "Belum ada promo.",
  promo_add: "Tambah Promo",
  promo_edit: "Edit Promo",
  promo_first_n_remaining: "{count} pembeli lagi yang berhak untuk promo!",
  promo_first_n_expired: "Promo telah habis",
  promo_discount: "Diskon",

  // Orders
  order_total_label: "Total Pesanan",
  order_approved_label: "Disetujui",
  order_revenue_label: "Estimasi Pendapatan",
  order_num: "#",
  order_name: "Nama",
  order_wa: "WA",
  order_address: "Alamat",
  order_items: "Item(s)",
  order_total: "Total",
  order_status: "Status",
  order_time: "Waktu",
  order_actions: "Aksi",
  order_approve: "Setujui",
  order_cancel: "Batalkan",
  order_send_wa: "Kirim WA",
  order_delete: "Hapus",
  order_status_pending: "Menunggu",
  order_status_approved: "Disetujui",
  order_status_deleted: "Dihapus",
  order_empty: "Belum ada pesanan.",
  order_confirm_delete: "Hapus pesanan ini?",
  order_export_disabled: "Ekspor tidak tersedia selama ada pesanan tersembunyi",

  // Summary tab
  summary_item: "Produk",
  summary_total: "Total Dipesan",
  summary_approved: "Disetujui",
  summary_pending: "Menunggu",
  summary_empty: "Belum ada data pesanan.",

  // Paywall
  paywall_banner: "🔒 {count} pesanan tersembunyi — Buka Sekarang",
  paywall_title: "Buka Pesanan Tersembunyi",
  paywall_per_order: "Per Pesanan",
  paywall_per_order_price: "Rp 500 / pesanan",
  paywall_pack_100: "Paket 100 Pesanan",
  paywall_pack_100_price: "Rp 20.000 flat",
  paywall_qty: "Jumlah Slot",
  paywall_total: "Total",
  paywall_qris: "QRIS",
  paywall_paid: "Saya Sudah Bayar",
  paywall_processing: "Memproses...",

  // Customer page
  customer_closed: "Sesi preorder ini sudah ditutup",
  customer_coupon_placeholder: "Masukkan kode kupon",
  customer_coupon_apply: "Pakai Kode",
  customer_coupon_invalid: "Kode kupon tidak valid",
  customer_coupon_applied: "Kupon berhasil diterapkan!",
  customer_order_now: "Pesan Sekarang",
  customer_items_selected: "item dipilih",
  customer_total: "Total",
  customer_full_name: "Nama Lengkap",
  customer_wa_number: "Nomor WhatsApp",
  customer_address: "Alamat",
  customer_send_wa: "Kirim via WhatsApp",
  customer_order_summary: "Ringkasan Pesanan",
  customer_success_title: "Pesanan Terkirim!",
  customer_success_desc: "Nomor antrian kamu:",
  customer_habis: "Habis",
  customer_promo_badge: "PROMO",
  customer_made_with: "Dibuat dengan Waitlistku",
  customer_countdown: "Pesanan ditutup dalam",
  customer_urgency: "🔥 Terbatas! Segera lakukan pemesanan sebelum kehabisan",
  countdown_days: "hari",
  countdown_hours: "jam",
  countdown_minutes: "menit",
  countdown_seconds: "detik",
  customer_qty: "Qty",
  customer_add_to_cart: "Tambah",

  // Item visibility
  item_visible: "Tampil",

  // Styling modal
  btn_styling: "Styling",
  styling_title: "Tampilan Halaman",
  styling_primary: "Warna Primer (Hero)",
  styling_accent: "Warna Aksen (Promo & Badge)",
};

export const en = {
  // Nav
  nav_home: "Home",
  nav_login: "Login",
  nav_register: "Register",
  nav_dashboard: "Dashboard",
  nav_logout: "Logout",

  // Landing
  hero_title: "Manage Your Business Preorders Easily",
  hero_subtitle:
    "Waitlistku helps SMEs organize preorder sessions, products, promotions, and customer orders — all in one place.",
  hero_cta_register: "Start Free",
  hero_cta_login: "Login",
  feature1_title: "Flexible Preorder Sessions",
  feature1_desc:
    "Create sessions with open/close dates, public links, and manage products easily.",
  feature2_title: "Auto Promos & Discounts",
  feature2_desc:
    "Set promos for first N buyers, time deadlines, or coupon codes.",
  feature3_title: "Orders via WhatsApp",
  feature3_desc:
    "Customers order directly, automatic confirmation sent via WhatsApp.",

  // Auth
  login_title: "Login to Waitlistku",
  login_email: "Email",
  login_password: "Password",
  login_submit: "Login",
  login_no_account: "Don't have an account?",
  login_register_link: "Register now",
  register_title: "Register Waitlistku",
  register_business: "Business Name",
  register_wa: "WhatsApp Number",
  register_email: "Email",
  register_password: "Password",
  register_confirm: "Confirm Password",
  register_submit: "Register",
  register_have_account: "Already have an account?",
  register_login_link: "Login here",

  // Dashboard
  dashboard_title: "My Preorder Sessions",
  dashboard_new: "Create New Session",
  dashboard_empty: "No sessions yet. Create your first one!",
  session_manage: "Manage",
  session_open_page: "Open Page",
  session_delete: "Delete",
  session_active: "Active",
  session_inactive: "Inactive",
  session_orders: "orders",
  session_slug: "Link",
  session_copy: "Copy",
  session_copied: "Copied!",

  // Session modal
  modal_new_session: "Create New Session",
  session_title_label: "Session Title",
  session_intro_label: "Intro Text",
  session_footer_label: "Footer Text",
  session_opens_at: "Opens At",
  session_closes_at: "Closes At",
  session_active_toggle: "Session Active",
  btn_save: "Save",
  btn_cancel: "Cancel",
  btn_create: "Create",
  btn_delete: "Delete",
  btn_edit: "Edit",
  btn_edit_settings: "Edit Settings",
  btn_add: "Add",
  btn_import: "Import XLSX",
  btn_template: "Download Template",
  btn_export: "Export Orders",

  // Tabs
  tab_products: "Products",
  tab_promos: "Promos",
  tab_orders: "Orders",
  tab_summary: "Summary",

  // Items
  item_name: "Product Name",
  item_desc: "Description",
  item_price: "Price",
  item_quota: "Quota",
  item_quota_limit: "Limit?",
  item_quota_amount: "Quota amount",
  item_no_quota: "Unlimited",
  item_empty: "No products yet.",
  item_add: "Add Product",
  item_edit: "Edit Product",

  // Promos
  promo_name: "Promo Name",
  promo_type: "Promo Type",
  promo_price: "Promo Price",
  promo_type_first_n: "First N Customers",
  promo_type_deadline: "Before Deadline",
  promo_type_coupon: "Coupon Code",
  promo_max_count: "Max Buyers",
  promo_deadline: "Deadline",
  promo_coupon_code: "Coupon Code",
  promo_applies_to: "Applies To",
  promo_applies_session: "Entire Session",
  promo_applies_item: "Specific Item",
  promo_select_item: "Select Item",
  promo_empty: "No promos yet.",
  promo_add: "Add Promo",
  promo_edit: "Edit Promo",
  promo_first_n_remaining: "{count} more buyers eligible for promo!",
  promo_first_n_expired: "Promo expired",
  promo_discount: "Discount",

  // Orders
  order_total_label: "Total Orders",
  order_approved_label: "Approved",
  order_revenue_label: "Est. Revenue",
  order_num: "#",
  order_name: "Name",
  order_wa: "WA",
  order_address: "Address",
  order_items: "Item(s)",
  order_total: "Total",
  order_status: "Status",
  order_time: "Time",
  order_actions: "Actions",
  order_approve: "Approve",
  order_cancel: "Cancel",
  order_send_wa: "Send WA",
  order_delete: "Delete",
  order_status_pending: "Pending",
  order_status_approved: "Approved",
  order_status_deleted: "Deleted",
  order_empty: "No orders yet.",
  order_confirm_delete: "Delete this order?",
  order_export_disabled: "Export unavailable while blurred rows exist",

  // Summary tab
  summary_item: "Product",
  summary_total: "Total Ordered",
  summary_approved: "Approved",
  summary_pending: "Pending",
  summary_empty: "No order data yet.",

  // Paywall
  paywall_banner: "🔒 {count} hidden orders — Unlock Now",
  paywall_title: "Unlock Hidden Orders",
  paywall_per_order: "Per Order",
  paywall_per_order_price: "Rp 500 / order",
  paywall_pack_100: "100 Order Pack",
  paywall_pack_100_price: "Rp 20,000 flat",
  paywall_qty: "Slot Quantity",
  paywall_total: "Total",
  paywall_qris: "QRIS",
  paywall_paid: "I've Already Paid",
  paywall_processing: "Processing...",

  // Customer page
  customer_closed: "This preorder session is closed",
  customer_coupon_placeholder: "Enter coupon code",
  customer_coupon_apply: "Apply",
  customer_coupon_invalid: "Invalid coupon code",
  customer_coupon_applied: "Coupon applied!",
  customer_order_now: "Order Now",
  customer_items_selected: "items selected",
  customer_total: "Total",
  customer_full_name: "Full Name",
  customer_wa_number: "WhatsApp Number",
  customer_address: "Address",
  customer_send_wa: "Send via WhatsApp",
  customer_order_summary: "Order Summary",
  customer_success_title: "Order Sent!",
  customer_success_desc: "Your queue number:",
  customer_habis: "Out of Stock",
  customer_promo_badge: "PROMO",
  customer_made_with: "Made with Waitlistku",
  customer_countdown: "Order closes in",
  customer_urgency: "🔥 Limited! Order now before it's too late",
  countdown_days: "days",
  countdown_hours: "hours",
  countdown_minutes: "minutes",
  countdown_seconds: "seconds",
  customer_qty: "Qty",
  customer_add_to_cart: "Add",

  // Item visibility
  item_visible: "Visible",

  // Styling modal
  btn_styling: "Styling",
  styling_title: "Page Styling",
  styling_primary: "Primary Color (Hero)",
  styling_accent: "Accent Color (Promo & Badge)",
};

export type LangKeys = keyof typeof id;
export type Lang = typeof id;
